
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "daily" 
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/packages/website"
    schedule:
      interval: "daily"     
    commit-message:
      prefix: "build"  
      include: "scope"         