projects:
  sarahbonzelet:
    schemaPath: graphql/schema.json
    includes:
      - amplify-src/js/graphql/**.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: amplify-src/js/graphql/
