
name: Integration
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm run-script setup:ci
      - name: Build sources
        run: npm run-script build:production
      - name: Lint sources
        run: npm run-script lint:ci
      - name: Run tests
        run: npm run-script test:ci
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0          