
name: Release to production
on:
  push:
    tags:
      - v*

env:
  NODE_VERSION: 16.x
  HUGO_VERSION: '0.92.2'

jobs:    
  deployment-production:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VESION }}
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true                
      - name: Install dependencies
        run: npm run-script setup:ci
      - name: Build sources in production profile
        run: npm run-script build:production      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}  
      - name: Deploy application
        run: npm run-script deploy:prod       
        env:
          CONTACT_FORM_RECIPIENT_EMAIL: ${{ secrets.CONTACT_FORM_RECIPIENT_EMAIL}}